<?php
class BookProduct extends Product {
    public $numPages;

    public $discount = 0;

    public function __construct($name, $price, $numPages)
    {
        parent::__construct($name, $price, $numPages);
        $this->numPages = $numPages;
    }

    public function getProduct()
    {
        $out = parent::getProduct(); // TODO: Change the autogenerated stub
        $out .= "Num Pages: {$this->numPages}";
        return $out;
    }

    public function getNumPages()
    {
        return $this->numPages;
    }
}